windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = float,class:^(rofi)$

windowrulev2 = opacity 0.85 0.85,class:^(Code)$
windowrulev2 = opacity 0.80 0.80, class:^(dolphin)$
windowrulev2 = opacity 0.80 0.80,class:^(thunar)$
windowrulev2 = opacity 0.80 0.80,class:^(nwg-look)$
windowrulev2 = opacity 0.80 0.80,class:^(Spotify)$
windowrulev2 = opacity 0.85 0.85,class:^(dev.zed.Zed)$

windowrulev2 = opacity 0.85 0.85,class:^(kitty)$

# windowrule v2 - size
#windowrulev2 = size 70% 70%, class:^(xdg-desktop-portal-gtk)$
